### ISSUE TITLE
Freeze constants

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#13]
I've seen bugs pop up in the past that resulted from code unintentionally mutating the value of a constant. Since I first saw this happen, I've adopted the approach of freezing newly defined constants, e.g. 

```
FOO = 'bar'.freeze
```

I know that the idea of replacing constants with methods has come up several times, so this may not be a huge deal, but does anyone have any thoughts of mentioning doing/not doing this in the style guide?

**Comment by kathleenlan** [comment]
Freezing constants sounds like a great idea. I think it doesn't hurt to mention this in the style guide - i.e. if we're going to use constants, we should always freeze them.

Although, like you mentioned, this point may be moot if we replace constants with methods. Is there any case when we would prefer using constants over methods? Our style guide does say 'Consider using methods instead of constants.' but I wonder if we should make a stronger statement that absolutely prefers methods over constants.

**Comment by adam-scimed** [comment]
Methods are harder to change than variables, but you can replace a method.
So if you really want it not to change a frozen constant might be best?

I kind of like the idea of using methods because it means that the API for
an object does not need to change even if something that was once constant
becomes more complex over time.

Adam

--
Adam Stasio
SciMed Solutions
327 West Main Street
Durham, NC 27701

adam.stasio@scimedsolutions.com
(919) 287-1817
(919) 680-3377 - Fax
--

**Comment by adam-scimed** [comment]
Approved!

**Comment by adam-scimed** [comment]
It sounds like this is no longer required as of Ruby 2.3.
