### ISSUE TITLE
Testing scopes

### ISSUE THREAD

**Issue by andycandrea** [SciMed/style-guide#20]
It seems like scopes tend to be explicitly test relatively rarely in our projects. At first, it seemed like testing them would require saving items to the database and checking for inclusion/exclusion of the appropriate rows in the resulting relation.

After thinking about it for a while, though, I think I have a decent solution. Instead of testing the scope itself, how about testing the SQL it generates? Here's a pro/con list I've thought of:

Pros:

* Doesn't actually hit the database (assuming we test `Model.scope.to_sql`) or require any data
* Can be simple (`expect(Model.scope.to_sql).to include "WHERE models.foo = 'bar'"`) or complex (`expect(Model.scope.to_sql).to eql "SELECT ... "` as needed

Cons:

* If the scope generates invalid SQL, the test won't catch it (e.g. if we change a column name relevant to the scope but don't change the scope or the test, the test will still pass since it doesn't actually hit the db)

On its own, that con is pretty troublesome. If we have good integration tests, though, I don't think it'd be nearly as much of a problem. Thoughts?

**Comment by kathleenlan** [comment]
Your suggestion of testing `Model.scope.to_sql` seems reasonable to me. :+1: 

Regarding the con, you mentioned, I think I may have a solution. If the (sql generated by the) scope is invalid, an `ActiveRecord::StatementInvalid` error is raised when the scope is invoked. So in addition to testing `Model.scope.to_sql`, we could also test that evaluating something like `Model.scope.first` does not raise an error.

```Ruby
e.g. 

it 'does not raise an error!' do
  expect { Model.scope.first }.not_to raise_error
end
```

There's two motivations for invoking `#first` on the scope. The first is that the scope seems to be lazily evaluated, so executing `Model.scope` for an invalid scope in an Rspec test doesn't raise an error. But when you 'use' the scope (e.g. by invoking a method like `#first`), the sql is then evaluated (and if it's invalid, the error is raised). The second motivation is better performance, particularly if the test database has a lot of records for Model.

What do you think?

**Comment by emerson-h** [comment]
Though I have tested scopes in this way in the past, I think it is a highly problematic approach for several reasons:

1.  Testing the generated SQL for a scope tests an implementation detail of a desired behavior rather than the behavior itself (i.e. testing SQL verifies that we perform a particular query but not that we get back what we need to get back)
1.  Machine generated SQL for complex scopes with many joins or includes is very complex, and the only way to get the entire SQL string is to call `#to_sql` from a console, and copy it into a spec file, in which case the test simply verifies that `#to_sql` continues to produce the same output.
1.  Testing that a condition string is included does not verify that it is included in the correct way.

Consider the following three versions of the same scope:

```ruby
# Version 1
  scope :with_appointments_within_one_week, -> {
    joins(:appointments).where('appointments.date < ?', 7.days.from_now)
  }

# Version 2
  scope :with_appointments_within_one_week, -> {
    includes(:appointments).references(:appointments).where(
      Appointment.arel_table[:date].lteq(7.days.from_now).to_sql
    )
  }

# Version 3 - contrived to demonstrate potential pitfalls
  scope :with_appointments_within_one_week, -> {
    includes(:appointments).references(:appointments).joins(
      User.arel_table.join(Appointment.arel_table, Arel::Nodes::OuterJoin).on(
        User.arel_table[:id].eq(Appointment.arel_table[:user_id]).and(
          Appointment.arel_table[:date].lteq(7.days.from_now)
        )
      ).join_sources
    )
  }
```

```SQL
-- Version 1
SELECT "users".*
FROM "users"
  INNER JOIN "appointments" ON "appointments"."user_id" = "users"."id"
WHERE (appointments.date < '2016-01-20 03:07:14.324299')

-- Version 2
SELECT
  "users"."id" AS t0_r0,
  "users"."first_name" AS t0_r1,
  "users"."last_name" AS t0_r2,
  "users"."email" AS t0_r3,
  "users"."password" AS t0_r4,
  "users"."date" AS t0_r5,
  "users"."created_at" AS t0_r6,
  "users"."updated_at" AS t0_r7,
  "appointments"."id" AS t1_r0,
  "appointments"."date" AS t1_r1,
  "appointments"."user_id" AS t1_r2,
  "appointments"."description" AS t1_r3,
  "appointments"."title" AS t1_r4,
  "appointments"."created_at" AS t1_r5,
  "appointments"."updated_at" AS t1_r6
FROM "users"
  LEFT JOIN "appointments" ON "appointments"."user_id" = "users"."id"
WHERE ("appointments"."date" <= '2016-01-20 03:07:14.324299')

-- Version 3
SELECT users.*
FROM users
  LEFT OUTER JOIN appointments ON users.id = appointments.user_id 
    AND appointments.date <= '2016-01-20 03:07:14.324299'
```

All three versions will make a test for the inclusion of the condition `"appointments"."date" <= '2016-01-20 03:07:14.324299'` pass.  This is problematic since only versions 1 and 2 return the expected results.  

Furthermore, a test that verifies the whole query must be changed every time a column is added to the table or every time an internal change in AREL makes the structure of the returned SQL change without changing its semantic meaning.

**Comment by emerson-h** [comment]
@kathleenlan It's worth noting that `#first` is actually highly non-performant on large tables since the query that RAILS generates includes `ORDER BY <table_primary_key> ASC`, which will require a scan of every row in a table.  

If you need a way to verify that at least one record exists within a relation, the following will work:

```ruby
SomeHugeTable.all_the_things.reorder('').limit(1).to_a.first
```

Most DBMS's that we use will begin to return unordered results as soon as the first one is extracted, which is often within a matter of milliseconds.  Here the `reorder` with a blank string forces Rails to remove any order clauses.  Since we don't care about what order the results are in and we just want the first result, the database can complete the query as soon as it has found any record that matches all of the condition of the scope.  

Calling `#to_a` is necessary because it forces the query to run.

**Comment by kathleenlan** [comment]
In a WTL, we decided to

* Prefer testing complicated scopes using an integration test that confirms the expected behavior against persisted records

* Extract complicated scopes into a QueryBuilder object for easier unit-testing
