### ISSUE TITLE
Discuss strategies for implementing FISMA compliant systems

### ISSUE THREAD

**Issue by anicholson44** [SciMed/style-guide#23]
(deleted)

**Comment by adam-scimed** [comment]
Andrew,

We often use the [PaperTrail](https://github.com/airblade/paper_trail) Gem to audit tables. Any other method of pretending to delete things has resulted in numerous bugs and problems. I would highly recommend staying away from any sort of "deleted_at" solution to the problem whenever possible.

**Comment by andycandrea** [comment]
@adam-scimed My understanding was that PaperTrail alone wasn't enough to be FISMA compliant (or wasn't enough to make the client happy).

I believe the specific case that you're referencing is when we used Paranoia for soft deletes, which overwrites `destroy` and sets default scopes on all models that specify `acts_as_paranoid`. Since that did cause us a lot of pain, we (Max and I) wrote our own soft deletion functionality into the newer FISMA project that Andrew and I have been working on.

So far, we haven't really had much trouble with it--unlike Paranoia, it does not use default scopes. However, Andrew brought up the point yesterday that not overwriting `destroy` might make it a little too easy to delete data (either unintentionally or on purpose), which I think is valid.

That said, if PaperTrail actually is enough for FISMA compliance and happy clients, I think this point may be moot.
