### ISSUE TITLE
Consider adding section for logging best practices in Rails

### ISSUE THREAD

**Issue by anicholson44** [SciMed/style-guide#24]
Some topics that may need to be covered:

- what logging framework to use
- what types of messages/events get logged at what level
- when to log and when not to log
- rules for logging in production
- managing log files (how long to keep old files, where to keep files if volume size is issue, how to clean up old files)
- what information to never log
- any log monitor tools being used (HoneyBadger, maybe more)

**Comment by dbernheisel** [comment]
We have the standard [Rails.logger](http://guides.rubyonrails.org/debugging_rails_applications.html#the-logger) to use for logging, and logging more is better than not logging enough. Obviously should not log sensitive information such as personally identifiable information or passwords, but anything else is generally fine. We're currently looking into a sophisticated logging tool like HoneyBadger.

We have found it to be very useful to put more logging into delayed_jobs or anything that is deferred.

**Comment by anicholson44** [comment]
Example of logger pattern:

   `1 class ExceptionLogger
   2   def self.log_error(e)
   3     Rails.logger.error("ERROR: #{e.message}")
   4     Rails.logger.error(e.backtrace.join("\n"))
   5   end
   6 end`

**Comment by dbernheisel** [comment]
Using discretion, background jobs make sense to log into different files instead of the standard Rails log. Keep note that there could be multiple background jobs and reading/writing IO could be blocking. This could be our interest for adopting a system like Honeybadger.

Another pattern we could use is to have another Logger subclass that hooks into notifiers for user or developer notifications.

Let's add a **Logging** section of the style guide and include these notes.

**Comment by kathleenlan** [comment]
This is closed. TODO: Add a `Logging` section to the style guide.
