### ISSUE TITLE
Use fully qualified names for ruby consts when possible

### ISSUE THREAD

**Issue by anicholson44** [SciMed/style-guide#36]
Instead of referencing classes using a relative name like `Foo`, use `::Foo` or `::Bar::Foo`. This is because `Foo` can find a different class depending on where the statement is evaluated, and what other classes are loaded in memory (and probably some additional unobvious factors), whereas `::Foo` will always pick out the `class Foo` defined in the project root, and `::Bar::Foo` will always pick out the `class Foo` defined in the `module Bar`.

**Comment by andycandrea** [comment]
This can probably only help, so I'm in favor.

**Comment by emerson-h** [comment]
It adds additional clutter that I'm not a huge fan of unless it's really needed.  

Ideally, tests should absolutely be in place that differentiate between `::Foo` and `Bar::Foo`.

**Comment by anicholson44** [comment]
There is no way to guarantee that your application will not run into these kinds of issues with tests because the incidence of these problems depends on what is loaded into memory, and that will be different when running tests and when running the application (particularly if the namespace conflicts span multiple components). Also, you can run into these problems in migrations and rake tasks, which are typically not under test (even if they are, the test environment for these will not reflect the runtime environment). Perhaps I'm leaning on the side of caution here but in my opinion absolute namespaces should be the default - I don't think you should have to prepend your constants with `::` to get the safe behavior, but all things considered I think writing those extra characters is worth it if we avoid a class of elusive and difficult to predict bugs.

**Comment by emerson-h** [comment]
I see several problems with that:

1. If your tests aren't mirroring your runtime environment then they are not valid tests.  When we run tests at the component level, they are in an isolated runtime that should include every dependency that component needs to operate.  Similarly when we run tests at the integration level in the main application, the test environment mimics the runtime.
2. Namespace conflicts should not span multiple components in a way that is not possible to guard against with specs unless there are circular dependencies, which is a larger problem.
3. Migrations that add data, unless it's added to a polymorphic association, should re-define model classes nested within the migration class as in 

```ruby
   class AddFooToBar < ActiveRecord::Migration
     class Bar < ActiveRecord::Base
       belongs_to: :foo
     end
     class Foo < ActiveRecord::Base; end
     
     add_column :bars, :foo_id, :integer
     
     Bar.reset_column_information
     Bar.each do |bar|
       bar.foo = Foo.create # some stuff here
       bar.save
     end
   end
```

This ensures that the Foo and Bar used in this migration are always scoped within the migration without the addition of a separate namespace module to encapsulate the migration models.

**Comment by anicholson44** [comment]
Consider a case where you have a class Foo::Bar in one component and Baz::Foo::Bar in another component, and these components are not dependencies of one another but are both included in the rails application. This could cause namespace issues at runtime which are not testable by unit tests. Maybe you could cover this by integration tests in theory but our integration tests will never provide 100% coverage. Why would we rely on integration tests which may not cover these errors when we can just use absolute namespaces and not worry about this entire class of errors?

**Comment by emerson-h** [comment]
@anicholson44 In the case you described, there is no way for `Foo::Bar` and `Baz::Foo::Bar` to collide with one another unless `Foo` is a dependency of `Baz`.  A reference to `Foo::Bar` in a rails application will resolve to `Foo::Bar` and never to `Baz::Foo::Bar`.  

However, within `Baz`, a call to `Foo::Bar` will resolve to `Baz::Foo::Bar`.  

Constant resolution works by climbing the namespace tree to `Object`, so in the case of this code:

```ruby
module Baz
  class Fizz
    def my_foo_magic(number)
      Foo::Bar.new.magic(number)
    end
    
    def foreign_foo_magic(number)
      ::Foo::Bar.new.magic(number)
    end
  end

  class Foo
    class Bar
      def magic(number)
        #something interesting
      end
    end
  end
end
```

the resolution of `Foo::Bar` in `Bar::Fizz#my_foo_magic` starts by looking at all of the descendants of `Fizz`. Since it does not contain a `Foo` namespace, the next parent, `Baz` is examined.  Since it contains a `Foo` namespace,  the resolution algorithm looks at the children of `Baz::Foo` for a `Bar` constant. 

When a module is prefixed with `::`, that is a directive that tells the constant resolution algorithm to start by examining children of `Object` for the desired constant, which is necessary if objects in the `Baz` namespace shown above need to use objects from the global `Foo` namespace rather than the local `Baz::Foo` namespace.

We should use fully qualified namespaces when referencing objects, but it should only be necessary to use absolute namespaces when we are dealing with the case outlined above.  The resolution algorithm will not look at `Baz::Foo` to find bar unless a reference to `Foo::Bar` comes from within the `Baz` module

**Comment by anicholson44** [comment]
See http://urbanautomaton.com/blog/2013/08/27/rails-autoloading-hell/ for a discussion on pitfalls of rails constant lookup. In an ideal project with 100% test coverage we _might_ not run into these but  I think it's worth the extra `::`s to **guarantee** that we won't run into these problems. We have in fact run into these types of problems in practice. Obviously I'm not advocating against good test coverage and sensible dependency structures, but I don't see the downside to using absolute constants.

**Comment by emerson-h** [comment]
The only case we've run into was the one I've described, which was an attempt to use the global `Foo::Bar` from within `Baz` without the prefix.  That is the only case where `::Foo::Bar` should be required.  

I am not advocating never using `::`; I am advocating only using it where required rather than adding a ton of visual noise to code with little practical advantage.  Additionally, there are some performance costs with each constant resolution needing to recurse down the object graph from the root each time.

**Comment by anicholson44** [comment]
Since there is resistance to this going in the style guide I'm closing this issue
