### ISSUE TITLE
For Discussion: do we prefer `alias` or `alias_method`?

### ISSUE THREAD

**Issue by jeffersonneel** [SciMed/style-guide#40]
The title says it all: do we have a preference toward using `alias` or `alias_method`?

My specific scenario came up when dealing with an association on a model. For example, if I have a model `Foo` that `belongs_to :bar`, should I use `alias_method :baz, :bar` or `alias baz bar`?

**Comment by dbernheisel** [comment]
Personally, I try to avoid aliasing. I don't need that indirection. Ain't nobody got time for that. I figure this is usually used with some clever (read: unnecessary) meta-programming.

But if I had to choose, I side with [Ernie Miller](https://ernie.io/2014/10/23/in-defense-of-alias/) and choose `alias` because it's more limited in how it operates and doesn't interact with other methods in inherited classes.

My advice: look for another way to solve the problem. Don't alias (if you can help it).

**Comment by adam-scimed** [comment]
- Prefer `alias` unless you have a reason that you need `alias_method`.
- Recommend avoid aliasing unless needed
- Recommend avoid aliasing controller action methods. It makes it more difficult to find where things are going.

**Comment by andycandrea** [comment]
One quick note: the community style guide has different use cases for both `alias` and `alias_method` (I don't think we typically write code that would fall under the suggested case for `alias_method`, though).
https://github.com/bbatsov/ruby-style-guide#alias-method-lexically
https://github.com/bbatsov/ruby-style-guide#alias-method

**Comment by aangott** [comment]
We can include the more nuanced approach from Andy's links.
